version: "3"

services:
    db:
        image: mysql:8.0.23
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8088:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
        restart: always
        depends_on:
            - "db"
        networks:
            - symfony
volumes:
    db_app:

networks:
    symfony:
